# Site settings
title: Millennial's
header-img: img/home-bg.jpg
email: contato@ifundamental.com.br
copyright_name: Fundamental Inc.
description: "Informações úteis para todos"
baseurl: ""
url: "http://blog.millennial.com.br"
twitter_username:
github_username:
facebook_username: bemillennials
email_username:  contato@ifundamental.com.br

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
