# Site Settings
baseurl: 		""
title: 			Inteligência Financeira

name: 				Inteligência Financeira
description: 	Conteúdo
url: 			"http://blog.millennial.com.br"

paginate: 		3
paginate_path: 	"blog/page:num"

twitter: 		indiqo
email: 			henriqueeliassilva@gmail.com.br

disqus: 		your_disqus_shortname
analytics: 		UA-XXXXXXX-Y

copyright: 		Copyright 2016 Fundametal Inc.

# Build Settings

permalink: pretty
gems: [jekyll-paginate]
