# Site Settings
baseurl: 		""
title: 			Fundamental Inc.

name: 				Fundamental Inc.
description: 	Conteúdo
url: 			"http://blog.millennial.com.br"

paginate: 		3
paginate_path: 	"blog/page:num"

twitter: 		indiqo
email: 			hello@indiqo.eu

disqus: 		your_disqus_shortname
analytics: 		UA-XXXXXXX-Y

copyright: 		Copyright 2014 Indiqo.

# Build Settings


gems: [jekyll-paginate]
